export const DIALOG_OPEN = "ui/DIALOG_OPEN";
export const DIALOG_CLOSE = "ui/DIALOG_CLOSE";

export const SNACKBAR_OPEN = "ui/SNACKBAR_OPEN";
export const SNACKBAR_CLOSE = "ui/SNACKBAR_CLOSE";

export const ACTION_BUTTON_OPEN = "ui/ACTION_BUTTON_OPEN";
export const ACTION_BUTTON_CLOSE = "ui/ACTION_BUTTON_CLOSE";
