import React from "react";
import Button from "@material-ui/core/Button";
import Dialog from "@material-ui/core/Dialog";
import DialogActions from "@material-ui/core/DialogActions";
import DialogContent from "@material-ui/core/DialogContent";
import DialogTitle from "@material-ui/core/DialogTitle";
import withMobileDialog from "@material-ui/core/withMobileDialog";
import { Form, Field } from "react-final-form";
import ListItem from "@material-ui/core/ListItem";
import ListItemText from "@material-ui/core/ListItemText";
import CloudUpload from "@material-ui/icons/CloudUpload";
import db from "modules/common/db";
import IDBExportImport from "indexeddb-export-import";

class ImportData extends React.Component {
  state = {
    open: false,
    data: {}
  };

  handleClickOpen = () => {
    this.setState({ open: true });
  };

  handleClose = () => {
    this.setState({ open: false });
  };

  onSubmit = async values => {
    if (this.state.data) {
      db.open().then(function() {
        let idb_db = db.backendDB();
        IDBExportImport.clearDatabase(idb_db, function(err) {
          console.log("in clear");
          console.log(this.state.data);
          if (!err)
            IDBExportImport.importFromJsonString(
              idb_db,
              this.state.data,
              function(err) {
                if (!err) console.log("Imported data successfully");
              }
            );
        }).catch(function(e) {
          console.error("Could not connect. " + e);
        });
      });
      this.handleClose();
    }
  };

  handleImportdata = file => {
    let fileReader;

    const handleFileRead = () => {
      this.setState({ data: fileReader.result });
      console.log(this.state.data);
    };

    fileReader = new FileReader();
    fileReader.onloadend = handleFileRead;
    fileReader.readAsText(file);
  };

  render() {
    const { fullScreen } = this.props;

    return (
      <React.Fragment>
        <ListItem button onClick={this.handleClickOpen}>
          <CloudUpload />
          <ListItemText primary="Import" />
        </ListItem>
        <Form
          onSubmit={this.onSubmit}
          render={({ handleSubmit, submitting, invalid }) => (
            <form onSubmit={handleSubmit}>
              <Dialog
                fullScreen={fullScreen}
                open={this.state.open}
                onClose={this.handleClose}
              >
                <DialogTitle>
                  Import data via JSON file generated by a previous data saving
                </DialogTitle>
                <DialogContent>
                  <input
                    name="data"
                    type="file"
                    accept=".json"
                    onChange={e => this.handleImportdata(e.target.files[0])}
                    required
                  />
                </DialogContent>
                <DialogActions>
                  <Button onClick={this.handleClose} color="primary">
                    Cancel
                  </Button>
                  <Button
                    type="submit"
                    disabled={submitting || invalid}
                    color="primary"
                    autoFocus
                    onClick={handleSubmit}
                  >
                    Import data
                  </Button>
                </DialogActions>
              </Dialog>
            </form>
          )}
        />
      </React.Fragment>
    );
  }
}

export default withMobileDialog()(ImportData);
