export const ADD_EXERCISE = "trainingSet/ADD_EXERCISE";
export const ADD_EXERCISE_SUCCESS = "trainingSet/ADD_EXERCISE_SUCCESS";
export const GET_EXERCISES = "trainingSet/GET_EXERCISES";
export const GET_EXERCISES_SUCCESS = "trainingSet/GET_EXERCISES_SUCCESS";

export const REMOVE_EXERCISE = "trainingSet/REMOVE_EXERCISE";
export const REMOVE_EXERCISE_SUCCESS = "trainingSet/REMOVE_EXERCISE_SUCCESS";

export const GET_EXERCISES_BY_TRAINING_SET_ID =
  "trainingSet/GET_EXERCISES_BY_TRAINING_SET_ID";
export const GET_EXERCISES_BY_TRAINING_SET_ID_SUCCESS =
  "trainingSet/GET_EXERCISES_BY_TRAINING_SET_ID_SUCCESS";
